runtime: nodejs12

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"
  GOOGLE_API_KEY: "example-gcs-bucket"

handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /
    static_dir: build

  - url: /.*
    redirect_http_response_code: 301
    script: auto
