//Auth context
export const AUTH_ERROR = 'AUTH_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const USER_LOADED = 'USER_LOADED'
export const LOGOUT = 'LOGOUT'

//Alert context
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const SET_ALERT = 'SET_ALERT'

//Station context
export const GET_ALL_STATIONS = 'GET_ALL_STATIONS'
export const GET_STATION = 'GET_STATION'
export const SET_POSITION = 'SET_POSITION'
export const SET_MAP_ZOOM = 'SET_MAP_ZOOM'
export const SET_CURRENT_STATION = 'SET_CURRENT_STATION'
export const GET_USER_STATIONS = 'GET_USER_STATIONS'
export const SET_MARKER_POSITION = 'SET_MARKER_POSITION'
export const ADD_STATION = 'ADD_STATION'
export const SET_EDIT_STATION = 'SET_EDIT_STATION'
export const EDIT_STATION = 'EDIT_STATION'
export const DELETE_STATION = 'DELETE_STATION'
export const GET_AVAIABLE_STATIONS = 'GET_AVAIABLE_STATIONS'
export const STATION_ERROR = 'STATION_ERROR'
export const GET_LATLANG = 'GET_LATLANG'


//Car context

export const GET_USER_CARS = "GET_USER_CARS"
export const ADD_CAR = "ADD_CAR"
export const GET_CAR = "GET_CAR"
export const EDIT_CAR = "EDIT_CAR"
export const DELETE_CAR = "DELETE_CAR"
export const CAR_ERROR = "CAR_ERROR"
export const SET_CURRENT_CAR = "SET_CURRENT_CAR"

//Reservation context

export const GET_RESERVATIONS_AS_DRIVER = 'GET_RESERVATIONS_AS_DRIVER'
export const GET_RESERVATIONS_AS_CHARGER = 'GET_RESERVATIONS_AS_CHARGER'
export const ADD_RESERVATION = 'ADD_RESERVATION'
export const DELETE_RESERVATION = 'DELETE_RESERVATION'
export const CONFIRM_RESERVATION = 'CONFIRM_RESERVATION'
export const REJECT_RESERVATION = 'REJECT_RESERVATION'
export const SET_DATE_FROM = 'SET_DATE_FROM'
export const SET_DATE_TO = 'SET_DATE_TO'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_MAP_MODAL = 'TOGGLE_MAP_MODAL'
export const TOGGLE_RESERVATION_MODAL = 'TOGGLE_RESERVATION_MODAL'
export const SET_RESERVATION_CAR = 'SET_RESERVATION_CAR'
export const RESERVATION_ERROR = 'RESERVATION_ERROR'
export const SET_ERROR = 'SET_ERROR'
export const SET_SUCCESS = 'SET_SUCCESS'